services:
  postgressql_security:
    image: postgres:latest
    container_name: security_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password2025
      POSTGRES_DB: security_db
    volumes:
      - /Users/daniel/Documents/Work/Maquisistema/Curso_NET/Volumenes/security_db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "1601:5432"

  vault:
    image: hashicorp/vault:1.17
    ports:
    - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "Ucyi1ziPEHQO4b"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "server -dev -dev-listen-address=0.0.0.0:8200"
    volumes:
      - /Users/daniel/Documents/Work/Maquisistema/Curso_NET/Volumenes/vault_security:/vault/file   

  redis:
      image: redis:7.4-alpine
      container_name: redis_auth
      restart: always
      ports:
          - "6379:6379"
      volumes:
          - /Users/daniel/Documents/Work/Maquisistema/Curso_NET/Volumenes/redis_security:/data
      command: ["redis-server", "--appendonly", "yes"]

  cap:
      image: tiago2/cap:latest
      container_name: cap-standalone
      ports:
          - "3000:3000"
      environment:
          ADMIN_KEY: 63f4945d921d599f27ae4fdf5bada3f1
          ENABLE_ASSETS_SERVER: "true"
          WIDGET_VERSION: "latest"
          WASM_VERSION: "latest"
          DATA_PATH: "./.data"
      restart: unless-stopped
      volumes:
          - /Users/daniel/Documents/Work/Maquisistema/Curso_NET/Volumenes/cap_security:/usr/src/app/.data